### ISSUE TITLE
Fix maven project structure

### ISSUE THREAD

**Issue by DasEtwas** [WillQi/PizzaServer#63]
Things that stuck out about the maven project:
* Modules have differing groupIds
* Adding PizzaServer as a dependency caused weird "dependency not found" errors for plugins
* During compilation, shading the jar warns about a bazillion files being doubled in the jar

**Comment by squeeglii** [comment]
Solved as of [cc4ccfb](https://github.com/PizzaServer/PizzaServer/commit/cc4ccfbef11635ed3ce14c70d0471cbadfd5102b) - Maven has been replaced by a new Gradle 7.4 buildscript
